Mat. 8
piotrskurzynski/biblia pull request #1447
Opened 2024-02-11 16:48 UTC by janstrakowski

2024-02-11 21:22 UTC, piotrskurzynski commented on 1632/40-mat/08.txt
> +A oto trędowáty przyƺedƺy pokłonił mu śię / mówiąc : PAnie! / jeſli chceƺ / możeƺ mię ocżyśćić.
Nie ma tu wykrzyknika, a zamiast dwukropka jest średnik.
![image](https://github.com/piotrskurzynski/biblia/assets/116842674/deec5758-7582-4c59-9540-0159082621ec)

2024-02-11 21:22 UTC, piotrskurzynski commented on 1632/40-mat/08.txt
> +Tedy mu rzekł JEzus : Pátrz ábyś nikomu nie powiádał; ále idź / ukáż śię kápłánowi / y ofiáruj dar on który przykázał Mojzeƺ / ná świádectwo przećiwko nim.
W zwykłym tekście wszystkie znaki interpunkcyjne, oprócz kropki, mają mieć z obydwu stron spacje.

2024-02-11 21:22 UTC, piotrskurzynski commented on 1632/40-mat/08.txt
> +A odpowiádájąc ſetnik / rzekł ; Pánie! / nie jeſtem godźien ábyś wƺedł pod dách mój ; ále tylko rzecż d ſłowo ; á będźie uzdrowiony ſługá mój.
Odnośników (takich jak to "d") nie wstawiamy do tekstu.

2024-02-11 21:22 UTC, piotrskurzynski commented on 1632/40-mat/08.txt
> +Bomći y ja cżłowiek pod mocą <i>innego</i>, májący pod ſobą żołnierze : y mówię temu : Idź / á idźie ; á drugiemu : Przyjdź / á przychodźi ; á ſłudze memu : Cżyń to / á cżyni.
Przecinki powinny być wewnątrz: `<i>innego,<i/>`.

2024-02-11 21:22 UTC, piotrskurzynski commented on 1632/40-mat/08.txt
> +Y rzekł do nich ; Przecżżeśćie bojáźliwi / o máłowierni? Tedy wſtáwƺy / zgromił y wiátry y morze / y ſtáło śię ućiƺenie wielkie.
Po „zgromił” nie ma „y”, tylko jest odnośnik „n”, a odnośników do tekstu nie wstawiamy.
![image](https://github.com/piotrskurzynski/biblia/assets/116842674/0c554764-1599-46dd-9c83-6a275bcbab3b)

2024-02-11 21:26 UTC, piotrskurzynski requested changes
2. Nie ma tu wykrzyknika, a zamiast dwukropka jest średnik.
![image](https://github.com/piotrskurzynski/biblia/assets/116842674/add8aeba-770f-49d9-866e-9c57b236015d)

4. W zwykłym tekście wszystkie znaki interpunkcyjne, oprócz kropki, mają mieć z obydwu stron spacje.

8. Odnośników (takich jak to "d") nie wstawiamy do tekstu.

9. Przecinki powinny być wewnątrz: `<i>innego,<i/>`.

26. Po „zgromił” nie ma „y”, tylko jest odnośnik „n”, a odnośników do tekstu nie wstawiamy.
![image](https://github.com/piotrskurzynski/biblia/assets/116842674/0d8dbf60-8d57-4189-a1dc-6d7f12f6fb8e)

2024-02-12 17:02 UTC, janstrakowski commented
Już poprawione

2024-02-12 22:05 UTC, piotrskurzynski approved these changes

2024-02-12 22:09 UTC, merged